import os
from dotenv import load_dotenv
from logger import logger

load_dotenv()


def _sanitize_tls_env() -> None:
    """
    Remove invalid TLS CA bundle env vars to prevent requests/botocore failures
    when a stale venv path is exported in the shell.
    """
    for key in ("REQUESTS_CA_BUNDLE", "SSL_CERT_FILE", "CURL_CA_BUNDLE"):
        value = (os.getenv(key) or "").strip()
        if not value:
            continue
        if not os.path.isfile(value):
            os.environ.pop(key, None)
            logger.warning("Ignoring invalid %s path: %s", key, value)


_sanitize_tls_env()


def _env_bool(name: str, default: bool) -> bool:
    val = os.getenv(name)
    if val is None:
        return default
    return val.strip().lower() in {"1", "true", "yes", "on"}


def _env_float(name: str, default: float) -> float:
    try:
        return float(os.getenv(name, str(default)))
    except Exception:
        return default


def _env_int(name: str, default: int) -> int:
    try:
        return int(os.getenv(name, str(default)))
    except Exception:
        return default


class Config:
    EXCHANGE = os.getenv("EXCHANGE", "COINDCX").strip().upper()
    if EXCHANGE not in {"COINDCX", "BINANCE"}:
        EXCHANGE = "COINDCX"

    COINDCX_API_KEY = os.getenv("COINDCX_API_KEY", "")
    COINDCX_API_SECRET = os.getenv("COINDCX_API_SECRET")
    BINANCE_API_KEY = os.getenv("BINANCE_API_KEY", "")
    BINANCE_API_SECRET = os.getenv("BINANCE_API_SECRET", os.getenv("BINANCE_SECRET_KEY"))

    API_KEY = BINANCE_API_KEY if EXCHANGE == "BINANCE" else COINDCX_API_KEY
    API_SECRET = BINANCE_API_SECRET if EXCHANGE == "BINANCE" else COINDCX_API_SECRET
    TRADING_MODE = os.getenv("TRADING_MODE", "SIMULATION")
    TRADING_PRODUCT = os.getenv("TRADING_PRODUCT", "SPOT").strip().upper()
    if TRADING_PRODUCT not in {"SPOT", "FUTURES", "OPTIONS"}:
        TRADING_PRODUCT = "SPOT"
    LLM_PROVIDER = os.getenv("LLM_PROVIDER", "BEDROCK").strip().upper()
    if LLM_PROVIDER not in {"BEDROCK", "OPENAI"}:
        LLM_PROVIDER = "BEDROCK"
    ENABLE_PARALLEL_PRODUCT_STRATEGIES = _env_bool("ENABLE_PARALLEL_PRODUCT_STRATEGIES", True)
    PARALLEL_PRODUCTS = [
        s.strip().upper()
        for s in os.getenv("PARALLEL_PRODUCTS", "SPOT,FUTURES,OPTIONS").split(",")
        if s.strip()
    ]
    PARALLEL_PRODUCTS = [p for p in PARALLEL_PRODUCTS if p in {"SPOT", "FUTURES", "OPTIONS"}] or ["SPOT", "FUTURES", "OPTIONS"]

    # ── Starting Capital ──
    STARTING_BALANCE_USDT = _env_float("STARTING_BALANCE_USDT", 1250.0)

    # ── Ensemble Weights ──
    WEIGHT_MOMENTUM = _env_float("WEIGHT_MOMENTUM", 0.35)
    WEIGHT_SWING = _env_float("WEIGHT_SWING", 0.35)
    WEIGHT_LLM = _env_float("WEIGHT_LLM", 0.30)

    # ── Confidence & Risk Gates ──
    MIN_ENSEMBLE_CONFIDENCE = _env_float("MIN_ENSEMBLE_CONFIDENCE", 0.45)
    LLM_CONFIDENCE_FLOOR = _env_float("LLM_CONFIDENCE_FLOOR", 0.55)
    ALGO_SIGNAL_THRESHOLD = _env_float("ALGO_SIGNAL_THRESHOLD", 0.10)
    EARLY_STOP_LOSS_PCT = _env_float("EARLY_STOP_LOSS_PCT", 0.003)
    LLM_POLL_INTERVAL_SECONDS = _env_int("LLM_POLL_INTERVAL_SECONDS", 600)

    # ── Dynamic Exit Strategy ──
    TAKE_PROFIT_PCT = _env_float("TAKE_PROFIT_PCT", 0.006)
    TRAILING_STOP_TRIGGER_PCT = _env_float("TRAILING_STOP_TRIGGER_PCT", 0.004)
    TRAILING_STOP_OFFSET_PCT = _env_float("TRAILING_STOP_OFFSET_PCT", 0.0025)

    # ── Timeframes ──
    MAX_TRADES_RUN = _env_int("MAX_TRADES_RUN", 1000)
    MANDATORY_EXIT_SECONDS = _env_int("MANDATORY_EXIT_SECONDS", 3600)
    CHECK_INTERVAL_SECONDS = _env_int("CHECK_INTERVAL_SECONDS", 60)
    POLL_INTERVAL_SECONDS = _env_int("POLL_INTERVAL_SECONDS", 60)
    COOLDOWN_MINUTES = _env_int("COOLDOWN_MINUTES", 5)

    # ── Runtime Safety / Cost Controls ──
    ENABLE_PERIODIC_REVIEW = _env_bool("ENABLE_PERIODIC_REVIEW", False)
    ENABLE_DISTILLATION = _env_bool("ENABLE_DISTILLATION", False)
    ENABLE_RUNTIME_GIT_PUSH = _env_bool("ENABLE_RUNTIME_GIT_PUSH", False)
    ENABLE_RUNTIME_CONFIG_AUTOTUNE = _env_bool("ENABLE_RUNTIME_CONFIG_AUTOTUNE", False)
    ENABLE_RETROSPECTIVE = _env_bool("ENABLE_RETROSPECTIVE", False)
    ENABLE_META_OPTIMIZER = _env_bool("ENABLE_META_OPTIMIZER", False)
    ENABLE_MISSED_OPPORTUNITY_ANALYZER = _env_bool("ENABLE_MISSED_OPPORTUNITY_ANALYZER", False)
    ENABLE_PYRAMIDING = _env_bool("ENABLE_PYRAMIDING", False)
    ENABLE_END_OF_SESSION_REVIEW = _env_bool("ENABLE_END_OF_SESSION_REVIEW", False)

    # Required by plan
    LLM_DAILY_BUDGET_USD = _env_float("LLM_DAILY_BUDGET_USD", 5.0)
    LLM_MAX_CALLS_PER_HOUR = _env_int("LLM_MAX_CALLS_PER_HOUR", 60)
    MAX_DAILY_DRAWDOWN_USD = _env_float("MAX_DAILY_DRAWDOWN_USD", 25.0)
    WARMUP_MIN_TICKS = max(5, _env_int("WARMUP_MIN_TICKS", 10))
    CHOPPY_EFFICIENCY_THRESHOLD = _env_float("CHOPPY_EFFICIENCY_THRESHOLD", 0.10)
    ALLOW_CHOPPY_HIGH_CONVICTION = _env_bool("ALLOW_CHOPPY_HIGH_CONVICTION", True)
    CHOPPY_MIN_VOTE_IMBALANCE = _env_float("CHOPPY_MIN_VOTE_IMBALANCE", 0.12)
    CHOPPY_MIN_CONFIDENCE = _env_float("CHOPPY_MIN_CONFIDENCE", 0.40)
    ENABLE_RL_WEIGHT_AGENT = _env_bool("ENABLE_RL_WEIGHT_AGENT", True)
    ENABLE_MLX_RL_AGENT = _env_bool("ENABLE_MLX_RL_AGENT", False)
    RL_EPSILON = _env_float("RL_EPSILON", 0.30)
    RL_MIN_EPSILON = _env_float("RL_MIN_EPSILON", 0.15)
    RL_EPSILON_DECAY = _env_float("RL_EPSILON_DECAY", 0.999)
    RL_LEARNING_RATE = _env_float("RL_LEARNING_RATE", 0.12)
    RL_WEIGHT_ADAPT_LR = _env_float("RL_WEIGHT_ADAPT_LR", 0.15)
    RL_MLX_LEARNING_RATE = _env_float("RL_MLX_LEARNING_RATE", 0.05)
    RL_MLX_HIDDEN_SIZE = _env_int("RL_MLX_HIDDEN_SIZE", 16)
    RL_PROFIT_REWARD_MULTIPLIER = _env_float("RL_PROFIT_REWARD_MULTIPLIER", 3.0)  # Boost winning trade rewards
    RL_LOSS_PENALTY_MULTIPLIER = _env_float("RL_LOSS_PENALTY_MULTIPLIER", 1.0)  # Keep loss penalties 1:1
    RL_OPPORTUNITY_COST_PENALTY = _env_float("RL_OPPORTUNITY_COST_PENALTY", 0.005)  # Reduced: keep skip rewards << trade rewards
    RL_SKIP_PENALTY_CAP = _env_float("RL_SKIP_PENALTY_CAP", 0.004)  # Upper bound for high-edge skips
    RL_SKIP_PENALTY_FLOOR = _env_float("RL_SKIP_PENALTY_FLOOR", 0.0003)  # Lower bound for low-edge skips
    RL_OPEN_TRADE_COST_PENALTY = _env_float("RL_OPEN_TRADE_COST_PENALTY", 0.002)  # Reduced from 0.005
    RL_SKIP_PRESSURE_START = _env_int("RL_SKIP_PRESSURE_START", 6)
    RL_SKIP_PRESSURE_STEP = _env_float("RL_SKIP_PRESSURE_STEP", 0.04)
    RL_SKIP_PRESSURE_MAX = _env_float("RL_SKIP_PRESSURE_MAX", 0.40)
    RL_SKIP_PRESSURE_EDGE_MIN = _env_float("RL_SKIP_PRESSURE_EDGE_MIN", 0.006)
    RL_MIN_TRADES_BEFORE_STRICT_GATES = _env_int("RL_MIN_TRADES_BEFORE_STRICT_GATES", 10)
    RL_MIN_CLOSED_TRADES_BEFORE_STRICT_GATES = _env_int("RL_MIN_CLOSED_TRADES_BEFORE_STRICT_GATES", 4)
    RL_UNDERSAMPLED_MIN_PRO_MULT = _env_float("RL_UNDERSAMPLED_MIN_PRO_MULT", 0.70)
    RL_UNDERSAMPLED_DIR_THRESHOLD_MULT = _env_float("RL_UNDERSAMPLED_DIR_THRESHOLD_MULT", 0.65)
    RL_UNDERSAMPLED_EDGE_THRESHOLD_MULT = _env_float("RL_UNDERSAMPLED_EDGE_THRESHOLD_MULT", 0.45)
    RL_FORCE_ENTRY_ON_SKIP_STREAK = _env_bool("RL_FORCE_ENTRY_ON_SKIP_STREAK", True)
    RL_FORCE_ENTRY_SKIP_STREAK = _env_int("RL_FORCE_ENTRY_SKIP_STREAK", 8)
    RL_FORCE_ENTRY_MAX_TRADES = _env_int("RL_FORCE_ENTRY_MAX_TRADES", 75)
    RL_FORCE_ENTRY_MIN_EDGE_PCT = _env_float("RL_FORCE_ENTRY_MIN_EDGE_PCT", 0.0015)
    RL_FORCE_ENTRY_MIN_STRATEGY_SCORE = _env_float("RL_FORCE_ENTRY_MIN_STRATEGY_SCORE", 0.15)
    RL_FORCE_ENTRY_MIN_VOTE_IMBALANCE = _env_float("RL_FORCE_ENTRY_MIN_VOTE_IMBALANCE", 0.15)
    # ── TradeGateAgent — TRADE vs SKIP contextual bandit ─────────────────────
    RL_GATE_WEIGHTS_FILE = os.path.join(os.path.dirname(__file__), "data", "gate_weights.json")
    GATE_COLD_THRESHOLD = _env_int("GATE_COLD_THRESHOLD", 5)   # states below this are explored freely
    GATE_LEARNING_RATE  = _env_float("GATE_LEARNING_RATE", 0.10)
    RL_SKIP_PENALTY_WARMUP_UPDATES = _env_int("RL_SKIP_PENALTY_WARMUP_UPDATES", 120)
    RL_SKIP_PENALTY_WARMUP_SCALE = _env_float("RL_SKIP_PENALTY_WARMUP_SCALE", 0.35)
    RL_SKIP_PENALTY_LOW_TRADE_SCALE = _env_float("RL_SKIP_PENALTY_LOW_TRADE_SCALE", 0.50)
    ENABLE_SENTIMENT_GATE = _env_bool("ENABLE_SENTIMENT_GATE", True)
    ENABLE_NEWS_LLM_SUMMARY = _env_bool("ENABLE_NEWS_LLM_SUMMARY", False)
    ENABLE_LLM_DECISION_REVIEW = _env_bool("ENABLE_LLM_DECISION_REVIEW", True)
    LLM_REVIEW_MIN_CONFIDENCE = _env_float("LLM_REVIEW_MIN_CONFIDENCE", 0.55)
    SENTIMENT_MIN_ABS_SCORE = _env_float("SENTIMENT_MIN_ABS_SCORE", 0.08)
    SENTIMENT_DIRECTIONAL_FLOOR = _env_float("SENTIMENT_DIRECTIONAL_FLOOR", 0.25)
    SENTIMENT_MIN_ARTICLES = _env_int("SENTIMENT_MIN_ARTICLES", 3)
    FUTURES_BLOCK_ON_OPPOSING_SENTIMENT = _env_bool("FUTURES_BLOCK_ON_OPPOSING_SENTIMENT", True)

    # Additional guardrails for deterministic-first flow
    MIN_NEW_CLOSED_TRADES_FOR_REVIEW = _env_int("MIN_NEW_CLOSED_TRADES_FOR_REVIEW", 10)
    MIN_NEW_CLOSED_TRADES_FOR_DISTILLATION = _env_int("MIN_NEW_CLOSED_TRADES_FOR_DISTILLATION", 10)
    FEE_SLIPPAGE_BUFFER_PCT = _env_float("FEE_SLIPPAGE_BUFFER_PCT", 0.12)
    MIN_EXPECTED_EDGE_PCT = _env_float("MIN_EXPECTED_EDGE_PCT", 0.005)
    MAX_RISK_PER_TRADE_PCT_BALANCE = _env_float("MAX_RISK_PER_TRADE_PCT_BALANCE", 0.18)
    MAX_CONSECUTIVE_LOSSES = _env_int("MAX_CONSECUTIVE_LOSSES", 10)
    FUTURES_MAX_LEVERAGE = max(1, _env_int("FUTURES_MAX_LEVERAGE", 8))
    FUTURES_MIN_LEVERAGE = max(1, min(_env_int("FUTURES_MIN_LEVERAGE", 1), FUTURES_MAX_LEVERAGE))
    FUTURES_MIN_COMPOSITE_SCORE = _env_float("FUTURES_MIN_COMPOSITE_SCORE", 0.25)
    FUTURES_MIN_CONFIDENCE = _env_float("FUTURES_MIN_CONFIDENCE", 0.40)
    FUTURES_MIN_REGIME_STRENGTH = _env_float("FUTURES_MIN_REGIME_STRENGTH", 0.05)
    FUTURES_TARGET_VOL_PCT_LOW = _env_float("FUTURES_TARGET_VOL_PCT_LOW", 0.02)
    FUTURES_TARGET_VOL_PCT_HIGH = _env_float("FUTURES_TARGET_VOL_PCT_HIGH", 0.70)
    FUTURES_EXTREME_VOL_PCT = _env_float("FUTURES_EXTREME_VOL_PCT", 1.80)
    FUTURES_MAX_SPREAD_PCT = _env_float("FUTURES_MAX_SPREAD_PCT", 0.35)
    FUTURES_MIN_VOLUME_24H = _env_float("FUTURES_MIN_VOLUME_24H", 20.0)
    FUTURES_OFF_HOURS_PENALTY = _env_float("FUTURES_OFF_HOURS_PENALTY", 0.04)
    FUTURES_LOSS_STREAK_PENALTY = _env_float("FUTURES_LOSS_STREAK_PENALTY", 0.03)
    FUTURES_SIZE_MIN_MULT = _env_float("FUTURES_SIZE_MIN_MULT", 0.90)
    FUTURES_SIZE_MAX_MULT = _env_float("FUTURES_SIZE_MAX_MULT", 1.80)
    FUTURES_WEIGHT_VOTE_IMBALANCE = _env_float("FUTURES_WEIGHT_VOTE_IMBALANCE", 0.22)
    FUTURES_WEIGHT_REGIME = _env_float("FUTURES_WEIGHT_REGIME", 0.16)
    FUTURES_WEIGHT_MOMENTUM = _env_float("FUTURES_WEIGHT_MOMENTUM", 0.16)
    FUTURES_WEIGHT_VOLATILITY = _env_float("FUTURES_WEIGHT_VOLATILITY", 0.14)
    FUTURES_WEIGHT_LIQUIDITY = _env_float("FUTURES_WEIGHT_LIQUIDITY", 0.14)
    FUTURES_WEIGHT_SENTIMENT = _env_float("FUTURES_WEIGHT_SENTIMENT", 0.10)
    FUTURES_WEIGHT_SESSION = _env_float("FUTURES_WEIGHT_SESSION", 0.08)
    OPTIONS_BLOCK_ON_OPPOSING_SENTIMENT = _env_bool("OPTIONS_BLOCK_ON_OPPOSING_SENTIMENT", True)
    OPTIONS_MIN_COMPOSITE_SCORE = _env_float("OPTIONS_MIN_COMPOSITE_SCORE", 0.25)
    OPTIONS_MIN_CONFIDENCE = _env_float("OPTIONS_MIN_CONFIDENCE", 0.40)
    OPTIONS_MIN_REGIME_STRENGTH = _env_float("OPTIONS_MIN_REGIME_STRENGTH", 0.04)
    OPTIONS_TARGET_VOL_PCT_LOW = _env_float("OPTIONS_TARGET_VOL_PCT_LOW", 0.03)
    OPTIONS_TARGET_VOL_PCT_HIGH = _env_float("OPTIONS_TARGET_VOL_PCT_HIGH", 0.95)
    OPTIONS_EXTREME_VOL_PCT = _env_float("OPTIONS_EXTREME_VOL_PCT", 2.20)
    OPTIONS_MAX_SPREAD_PCT = _env_float("OPTIONS_MAX_SPREAD_PCT", 0.40)
    OPTIONS_MIN_VOLUME_24H = _env_float("OPTIONS_MIN_VOLUME_24H", 20.0)
    OPTIONS_OFF_HOURS_PENALTY = _env_float("OPTIONS_OFF_HOURS_PENALTY", 0.05)
    OPTIONS_LOSS_STREAK_PENALTY = _env_float("OPTIONS_LOSS_STREAK_PENALTY", 0.04)
    OPTIONS_SIZE_MIN_MULT = _env_float("OPTIONS_SIZE_MIN_MULT", 0.70)
    OPTIONS_SIZE_MAX_MULT = _env_float("OPTIONS_SIZE_MAX_MULT", 1.35)
    OPTIONS_WEIGHT_VOTE_IMBALANCE = _env_float("OPTIONS_WEIGHT_VOTE_IMBALANCE", 0.16)
    OPTIONS_WEIGHT_REGIME = _env_float("OPTIONS_WEIGHT_REGIME", 0.13)
    OPTIONS_WEIGHT_MOMENTUM = _env_float("OPTIONS_WEIGHT_MOMENTUM", 0.12)
    OPTIONS_WEIGHT_VOLATILITY = _env_float("OPTIONS_WEIGHT_VOLATILITY", 0.24)
    OPTIONS_WEIGHT_LIQUIDITY = _env_float("OPTIONS_WEIGHT_LIQUIDITY", 0.12)
    OPTIONS_WEIGHT_SENTIMENT = _env_float("OPTIONS_WEIGHT_SENTIMENT", 0.09)
    OPTIONS_WEIGHT_SESSION = _env_float("OPTIONS_WEIGHT_SESSION", 0.07)
    OPTIONS_WEIGHT_EDGE = _env_float("OPTIONS_WEIGHT_EDGE", 0.07)
    SPOT_LONG_ONLY = _env_bool("SPOT_LONG_ONLY", False)
    SPOT_BLOCK_ON_OPPOSING_SENTIMENT = _env_bool("SPOT_BLOCK_ON_OPPOSING_SENTIMENT", False)
    SPOT_MIN_COMPOSITE_SCORE = _env_float("SPOT_MIN_COMPOSITE_SCORE", 0.25)
    SPOT_MIN_CONFIDENCE = _env_float("SPOT_MIN_CONFIDENCE", 0.40)
    SPOT_MIN_REGIME_STRENGTH = _env_float("SPOT_MIN_REGIME_STRENGTH", 0.04)
    SPOT_TARGET_VOL_PCT_LOW = _env_float("SPOT_TARGET_VOL_PCT_LOW", 0.015)
    SPOT_TARGET_VOL_PCT_HIGH = _env_float("SPOT_TARGET_VOL_PCT_HIGH", 0.65)
    SPOT_EXTREME_VOL_PCT = _env_float("SPOT_EXTREME_VOL_PCT", 1.60)
    SPOT_MAX_SPREAD_PCT = _env_float("SPOT_MAX_SPREAD_PCT", 0.32)
    SPOT_MIN_VOLUME_24H = _env_float("SPOT_MIN_VOLUME_24H", 20.0)
    SPOT_OFF_HOURS_PENALTY = _env_float("SPOT_OFF_HOURS_PENALTY", 0.03)
    SPOT_LOSS_STREAK_PENALTY = _env_float("SPOT_LOSS_STREAK_PENALTY", 0.03)
    SPOT_SIZE_MIN_MULT = _env_float("SPOT_SIZE_MIN_MULT", 0.80)
    SPOT_SIZE_MAX_MULT = _env_float("SPOT_SIZE_MAX_MULT", 1.55)
    SPOT_WEIGHT_TREND = _env_float("SPOT_WEIGHT_TREND", 0.25)
    SPOT_WEIGHT_MOMENTUM = _env_float("SPOT_WEIGHT_MOMENTUM", 0.20)
    SPOT_WEIGHT_VOLATILITY = _env_float("SPOT_WEIGHT_VOLATILITY", 0.15)
    SPOT_WEIGHT_LIQUIDITY = _env_float("SPOT_WEIGHT_LIQUIDITY", 0.15)
    SPOT_WEIGHT_SENTIMENT = _env_float("SPOT_WEIGHT_SENTIMENT", 0.10)
    SPOT_WEIGHT_SESSION = _env_float("SPOT_WEIGHT_SESSION", 0.10)
    SPOT_WEIGHT_PERFORMANCE = _env_float("SPOT_WEIGHT_PERFORMANCE", 0.05)

    # ── Periodic Self-Improvement ──
    PERIODIC_REVIEW_TRADES = _env_int("PERIODIC_REVIEW_TRADES", 5)
    PERIODIC_REVIEW_SECONDS = _env_int("PERIODIC_REVIEW_SECONDS", 600)

    # ── Position Sizing ──
    MAX_POSITION_SIZE_USDT = _env_float("MAX_POSITION_SIZE_USDT", 250)
    MIN_POSITION_SIZE_USDT = _env_float("MIN_POSITION_SIZE_USDT", 125)
    STOP_LOSS_PCT = _env_float("STOP_LOSS_PCT", 1.0)
    MAX_POSITIONS = _env_int("MAX_POSITIONS", 3)

    # ── Entry Filters ──
    MIN_24H_DIP_PCT = _env_float("MIN_24H_DIP_PCT", -1.0)
    ENTRY_NEAR_LOW_PCT = _env_float("ENTRY_NEAR_LOW_PCT", 0.02)
    MOMENTUM_WINDOW_MINS = _env_int("MOMENTUM_WINDOW_MINS", 60)
    MIN_MOMENTUM_PCT = _env_float("MIN_MOMENTUM_PCT", 0.0005)

    # ── AWS Bedrock LLM ──
    BEDROCK_MODEL_ID = os.getenv("BEDROCK_MODEL_ID", "us.anthropic.claude-haiku-4-5-20251001-v1:0")
    LOCAL_LLM_ENABLED = _env_bool("LOCAL_LLM_ENABLED", False)
    LOCAL_LLM_MODEL_PATH = os.getenv("LOCAL_LLM_MODEL_PATH", "")
    LOCAL_LLM_MODEL_NAME = os.getenv("LOCAL_LLM_MODEL_NAME", "local-llama")
    LOCAL_LLM_TEMPERATURE = _env_float("LOCAL_LLM_TEMPERATURE", 0.1)
    LOCAL_LLM_MAX_TOKENS = _env_int("LOCAL_LLM_MAX_TOKENS", 200)
    BEDROCK_INFERENCE_PROFILE_ID = os.getenv("BEDROCK_INFERENCE_PROFILE_ID", "")
    AWS_DEFAULT_REGION = os.getenv("AWS_DEFAULT_REGION", "us-east-1")
    HAIKU_MODEL_ID = os.getenv("HAIKU_MODEL_ID", "us.anthropic.claude-haiku-4-5-20251001-v1:0")
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
    OPENAI_MODEL_ID = os.getenv("OPENAI_MODEL_ID", "gpt-4.1-mini")
    OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1")
    OPENAI_NEWS_SUMMARY_MODEL_ID = os.getenv("OPENAI_NEWS_SUMMARY_MODEL_ID", "gpt-4.1-mini")
    ALPHAVANTAGE_API_KEY = os.getenv("ALPHAVANTAGE_API_KEY", "")
    CRYPTOCOMPARE_API_KEY = os.getenv("CRYPTOCOMPARE_API_KEY", "")

    # Approximate costs (USD / 1M tokens), used for runtime budgeting
    SONNET_INPUT_USD_PER_1M = _env_float("SONNET_INPUT_USD_PER_1M", 3.00)
    SONNET_OUTPUT_USD_PER_1M = _env_float("SONNET_OUTPUT_USD_PER_1M", 15.00)
    HAIKU_INPUT_USD_PER_1M = _env_float("HAIKU_INPUT_USD_PER_1M", 0.80)
    HAIKU_OUTPUT_USD_PER_1M = _env_float("HAIKU_OUTPUT_USD_PER_1M", 4.00)
    OPENAI_INPUT_USD_PER_1M = _env_float("OPENAI_INPUT_USD_PER_1M", 0.40)
    OPENAI_OUTPUT_USD_PER_1M = _env_float("OPENAI_OUTPUT_USD_PER_1M", 1.60)
    OPENAI_NEWS_SUMMARY_INPUT_USD_PER_1M = _env_float("OPENAI_NEWS_SUMMARY_INPUT_USD_PER_1M", OPENAI_INPUT_USD_PER_1M)
    OPENAI_NEWS_SUMMARY_OUTPUT_USD_PER_1M = _env_float("OPENAI_NEWS_SUMMARY_OUTPUT_USD_PER_1M", OPENAI_OUTPUT_USD_PER_1M)

    # ── API ──
    COINDCX_REST_BASE_URL = os.getenv("COINDCX_REST_BASE_URL", "https://api.coindcx.com")
    BINANCE_REST_BASE_URL = os.getenv("BINANCE_REST_BASE_URL", "https://api.binance.us")
    DEFAULT_REST_BASE_URL = BINANCE_REST_BASE_URL if EXCHANGE == "BINANCE" else COINDCX_REST_BASE_URL
    REST_BASE_URL = os.getenv("REST_BASE_URL", DEFAULT_REST_BASE_URL)

    # ── Asset Focus ──
    BLUE_CHIP_WHITELIST = [
        s.strip().upper()
        for s in os.getenv("BLUE_CHIP_WHITELIST", "BTCUSDT,ETHUSDT,SOLUSDT,ETHBTC,SOLBTC,SOLETH").split(",")
        if s.strip()
    ]

    @classmethod
    def is_symbol_allowed(cls, symbol: str) -> bool:
        return str(symbol).upper() in set(cls.BLUE_CHIP_WHITELIST)


config = Config()
